---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
pages:
- _posts/finally-a-free-and-awesome-personal-blog-experience.md
- _posts/things-i-learned-by-going-remote.md
